BEGIN;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastSeenAt" TIMESTAMP(3);
UPDATE "User" SET "lastSeenAt" = NOW() WHERE "lastSeenAt" IS NULL;
ALTER TABLE "User" ALTER COLUMN "lastSeenAt" SET DEFAULT NOW();
ALTER TABLE "User" ALTER COLUMN "lastSeenAt" SET NOT NULL;

ALTER TABLE "realtor_auto_reply_settings" ADD COLUMN IF NOT EXISTS "enabled" BOOLEAN NOT NULL DEFAULT false;

COMMIT;
